### ISSUE TITLE
make:aggregate-root command not found

### ISSUE THREAD

**Issue by dallincoons** [spatie/laravel-eventsauce#10]
I'm running `composer require eventsauce/laravel-eventsauce` (which pulls dev-master as the latest version), looks like I'm missing some stuff, for example I seem to be missing the MakeAggregateRootCommand. I guess I don't know enough about composer because I thought dev-master would just pull in the latest from the master branch.

**Comment by freekmurze** [comment]
`composer require eventsauce/laravel-eventsauce` should pull in the latest stable version, not `dev-master`. Are you sure you meet all requirements? Are you running the right PHP version?

**Comment by dallincoons** [comment]
@freekmurze when running just `composer require eventsauce/laravel-eventsauce` I get `Could not find a version of package eventsauce/laravel-eventsauce matching your minimum-stability (stable)`

I'm not seeing any versions other than dev-master on packagist https://packagist.org/packages/eventsauce/laravel-eventsauce

**Comment by freekmurze** [comment]
O, you're pulling in the wrong package 😄 

This is `spatie/laravel-eventsauce`, not `eventsauce/laravel-eventsauce`.

**Comment by freekmurze** [comment]
Fixed it in the readme 👍 

Thanks for bringing this to my attention.

**Comment by dallincoons** [comment]
Aaah, I thought I was going crazy 😄

**Comment by freekmurze** [comment]
That can still be the case 😄
