### ISSUE TITLE
PHP 7.2 support?

### ISSUE THREAD

**Issue by marcusmoore** [spatie/laravel-eventsauce#11]
Hello,

I noticed the package requires php 7.3 (via [this commit](https://github.com/spatie/laravel-eventsauce/commit/92e6eac9f3f518e4b699923b8b01f91e339fb4a6)). At first glance, it looks like support for 7.2 was dropped in order to support trailing commas in functions.

I know Spatie likes to stay on the ball with the latest and greatest but would you be consider a PR to support php 7.2 again?

Thanks!

**Comment by freekmurze** [comment]
I'd rather have you upgrading to PHP 7.3 😄

**Comment by marcusmoore** [comment]
Fair enough @freekmurze! Thanks for your open-source work!
